#!/bin/bash
# E22: leave-one-out pre-training -> target fine-tuning -> reporting evals, chained in ONE job (CHANGES.md items 77,
# 79). One chain per (rotation target, seed 0-2) per node: pre-train on the other four hands only (target gated at
# 100 on its _K50kr store, E19 recipe, ~7 h), then fine-tune from its final epoch (policy_latest.pt) on the target
# 50k (lr 1e-5, 10 epochs, ~1.7 h) while the pre-train is scored, then the fine-tune evals (~0.5 h).
# 15 chains = 3 jobs x 5 nodes, PACK=1, limit 12:00 (~9.5 h expected). Run from the repo root on a LOGIN node.
# Manifests (gitignored) are regenerated by:
#
#   python scripts/build_ambient_manifest.py --families InHand-Rotation --leave-one-out --seeds 0 1 2 \
#       --size 50kr --root outputs/diffusion/loo_r --out slurm_jobs/loo_pretrain_manifest.json
#   python scripts/build_finetune_manifest.py --families InHand-Rotation --src-tag loo --init policy_latest.pt \
#       --seeds 0 1 2 --lrs 1e-5 --size 50kr --src-root outputs/diffusion/loo_r --root outputs/diffusion/loo_r_ft \
#       --out slurm_jobs/loo_finetune_manifest.json
#   python scripts/build_chain_manifest.py --pre slurm_jobs/loo_pretrain_manifest.json \
#       --ft slurm_jobs/loo_finetune_manifest.json --out slurm_jobs/loo_chain_manifest.json
#   bash slurm_jobs/submit_e22_loo.sh
#
# Evals inside the chain are resumable: if the job times out after training, re-score with
# slurm_jobs/vista_eval_checkpoints.sbatch (RUNS='diffusion/loo_r_ft/*', EVAL_SEED=..., CROSS=1 as needed).
set -euo pipefail
cd "$(dirname "$0")/.."
[[ -f slurm_jobs/loo_chain_manifest.json ]] || { echo "build slurm_jobs/loo_chain_manifest.json first (see header)" >&2; exit 1; }
sbatch -A ASC26008 -p gh -N 5 --array=0-2 -t 12:00:00 --job-name=loo-chain \
  --export=ALL,MANIFEST=slurm_jobs/loo_chain_manifest.json,PACK=1 slurm_jobs/vista_train_manifest.sbatch
