#!/bin/bash
# E23: grasp ambient sigma sweep on random-draw 50k targets (CHANGES.md item 80). Per target hand (target 50kr +
# the other four at 1M, term-aligned, frozen family min/max configs/norm_grasp_minmax.json): sigma 0,10,...,100 x
# seed 0, plus sigma 0/100 x seeds 1-2 = 75 runs. Each node trains one run (E19 recipe, ~7 h) and then scores its
# best_val at eval seeds 1234 and 4321 (100 envs x 1500 steps). 5 jobs x 15 nodes, limit 9:00.
# Run from the repo root on a LOGIN node. Manifests (gitignored) are regenerated by:
#
#   python scripts/build_ambient_manifest.py --families Grasp --sigmas 0 10 20 30 40 50 60 70 80 90 100 --seeds 0 \
#       --size 50kr --root outputs/diffusion/ambient_ta_gr --out slurm_jobs/grasp_sweep_s0_manifest.json
#   python scripts/build_ambient_manifest.py --families Grasp --sigmas 0 100 --seeds 1 2 \
#       --size 50kr --root outputs/diffusion/ambient_ta_gr --out slurm_jobs/grasp_sweep_s12_manifest.json
#   python -c "import json; a=json.load(open('slurm_jobs/grasp_sweep_s0_manifest.json')); \
#       b=json.load(open('slurm_jobs/grasp_sweep_s12_manifest.json')); \
#       json.dump(a+b, open('slurm_jobs/grasp_sweep_manifest.json','w'), indent=1)"
#   python scripts/build_chain_manifest.py --pre slurm_jobs/grasp_sweep_manifest.json \
#       --out slurm_jobs/grasp_sweep_chain_manifest.json
#   bash slurm_jobs/submit_e23_grasp_sweep.sh
set -euo pipefail
cd "$(dirname "$0")/.."
M=slurm_jobs/grasp_sweep_chain_manifest.json
[[ -f $M ]] || { echo "build $M first (see header)" >&2; exit 1; }
sbatch -A ASC26008 -p gh -N 15 --array=0-4 -t 09:00:00 --job-name=grasp-sweep \
  --export=ALL,MANIFEST=$M,PACK=1 slurm_jobs/vista_train_manifest.sbatch
