#!/bin/bash
# E22: leave-one-out pre-training, then target-only fine-tuning (CHANGES.md item 77). For each rotation target and
# seed 0-2: pre-train on the OTHER four hands only (target gated at 100 on its _K50kr pooled store, others at 0;
# E19 recipe, 784k steps), then fine-tune from the final epoch (policy_latest.pt) on the target's 50k, lr 1e-5,
# 10 epochs (as E21). Run from the repo root on a Vista LOGIN node. Manifests (gitignored) are regenerated by:
#
#   python scripts/build_ambient_manifest.py --families InHand-Rotation --leave-one-out --seeds 0 1 2 \
#       --size 50kr --root outputs/diffusion/loo_r --out slurm_jobs/loo_pretrain_manifest.json
#   python scripts/build_finetune_manifest.py --families InHand-Rotation --src-tag loo --init policy_latest.pt \
#       --seeds 0 1 2 --lrs 1e-5 --size 50kr --src-root outputs/diffusion/loo_r --root outputs/diffusion/loo_r_ft \
#       --out slurm_jobs/loo_finetune_manifest.json
#   bash slurm_jobs/submit_e22_loo.sh            # DRY=1 prints the sbatch lines only
#   PRE_ID=1060945 bash slurm_jobs/submit_e22_loo.sh   # pre-train already queued (2026-10-09): submit the rest
#
# Jobs (12 queue slots, peak 15 nodes). Evals ~5.8 min each at 4 per GH200 (ev-base4321, 2026-10-08):
#   pre      15 pre-trains, PACK=1, 3 x 5-node jobs, ~6.7-7.0 h (as 1049683), limit 9:00
#   ft       15 fine-tunes, PACK=1, 3 x 5-node jobs, ~1h35-1h46 (as 1056188), limit 2:30      after pre
#   evpre    pre-trains last0 on their (unseen) target, seed 4321: zero-shot, 15 evals      after pre
#   evprex   pre-trains last0 on the 4 hands they trained on, seed 4321, 60 evals          after evpre
#   evft4321 fine-tunes best_rollout/best_val/last0, own target, seed 4321, 45 evals        after ft
#   evft1234 same at seed 1234                                                             after ft
#   evftx    fine-tunes best_val/last0 on the other 4 hands, seed 4321 (forgetting), 120   after evft4321
# Evals are resumable (rows already written are skipped): resubmit the same line if one times out.
# If a line fails, do NOT rerun the script (earlier jobs are queued): submit the remaining lines by hand.
set -euo pipefail
cd "$(dirname "$0")/.."
A=(-A ASC26008 -p gh)
EVAL=slurm_jobs/vista_eval_checkpoints.sbatch
PRE=diffusion/loo_r/*
FT=diffusion/loo_r_ft/*

sub() {  # sub <name> <sbatch args...>; echoes the job id
  if [[ -n "${DRY:-}" ]]; then echo "sbatch --parsable ${*:2}" >&2; echo "DRY_$1"; return; fi
  shift
  # TACC's sbatch wrapper prints a banner (lines of dashes, project info) on stdout as well, so keep only the
  # numeric job-id line; fail loudly if there is none (CHANGES.md item 78).
  local out id
  out=$(sbatch --parsable "$@") || { echo "$out" >&2; return 1; }
  id=$(grep -oE '^[0-9]+' <<< "$out" | tail -1)
  [[ -n "$id" ]] || { echo "no job id in sbatch output:" >&2; echo "$out" >&2; return 1; }
  echo "$id"
}

for m in loo_pretrain loo_finetune; do
  [[ -f slurm_jobs/${m}_manifest.json ]] || { echo "build slurm_jobs/${m}_manifest.json first (see header)" >&2; exit 1; }
done
# PRE_ID=<job id> reuses an already-queued pre-train job instead of submitting it again.
if [[ -n "${PRE_ID:-}" ]]; then P=$PRE_ID; else
P=$(sub pre "${A[@]}" -N 5 --array=0-2 -t 09:00:00 --job-name=loo-pre \
  --export=ALL,MANIFEST=slurm_jobs/loo_pretrain_manifest.json,PACK=1 slurm_jobs/vista_train_manifest.sbatch)
fi
F=$(sub ft "${A[@]}" -N 5 --array=0-2 -t 02:30:00 --job-name=loo-ft --dependency=afterany:$P \
  --export=ALL,MANIFEST=slurm_jobs/loo_finetune_manifest.json,PACK=1 slurm_jobs/vista_train_manifest.sbatch)
E1=$(sub evpre "${A[@]}" --array=0 -t 01:00:00 --job-name=ev-loopre --dependency=afterany:$P \
  --export=ALL,RUNS="$PRE",WHICH=last0,EVAL_SEED=4321 $EVAL)
E2=$(sub evprex "${A[@]}" --array=0 -t 02:00:00 --job-name=ev-looprex --dependency=afterany:$E1 \
  --export=ALL,RUNS="$PRE",WHICH=last0,EVAL_SEED=4321,CROSS=1 $EVAL)
E3=$(sub evft4321 "${A[@]}" --array=0 -t 02:00:00 --job-name=ev-looft4321 --dependency=afterany:$F \
  --export=ALL,RUNS="$FT",EVAL_SEED=4321 $EVAL)
E4=$(sub evft1234 "${A[@]}" --array=0 -t 02:00:00 --job-name=ev-looft1234 --dependency=afterany:$F \
  --export=ALL,RUNS="$FT",EVAL_SEED=1234 $EVAL)
E5=$(sub evftx "${A[@]}" --array=0-1 -t 02:00:00 --job-name=ev-looftx --dependency=afterany:$E3 \
  --export=ALL,RUNS="$FT",WHICH=best_val:last0,EVAL_SEED=4321,CROSS=1 $EVAL)
echo "pre=$P ft=$F evpre=$E1 evprex=$E2 evft4321=$E3 evft1234=$E4 evftx=$E5"
