#!/bin/bash
# E24: fine-tune the E23 grasp runs on their target only (CHANGES.md item 81): sigma 0 (co-trained) x seeds 0-2, and
# each hand's best ambient sigma (best E23 best_val success rate among sigma 10-90 at eval seed 1234, seed 0 only:
# Allegro 10, LEAP 20, Shadow 10, Sharpa 10, Wuji 10) = 20 fine-tunes. Recipe as E21 (from policy_best_val.pt,
# target-only gating, lr 1e-5, 10 epochs). Each node then scores best_rollout/best_val/last0 at seeds 1234 and 4321
# and best_val/last0 on the other four hands at 4321. 4 jobs x 5 nodes, limit 3:00 (fine-tune ~1h35-1h46 as
# 1056188 + evals ~0.5 h); waits for the E23 sweep (1061197) so every source run is final.
# Run from the repo root on a LOGIN node. Manifests (gitignored) are regenerated by:
#
#   A="--families Grasp --lrs 1e-5 --size 50kr --src-root outputs/diffusion/ambient_ta_gr --root outputs/diffusion/ambient_ta_gr_ft"
#   python scripts/build_finetune_manifest.py $A --src-sigmas 0 --seeds 0 1 2 --out slurm_jobs/grasp_ft_s0_manifest.json
#   for hs in Allegro:10 LEAP:20 Shadow:10 Sharpa:10 Wuji:10; do python scripts/build_finetune_manifest.py $A \
#       --hands ${hs%:*} --src-sigmas ${hs#*:} --seeds 0 --out /tmp/ft_${hs%:*}.json; done
#   # concatenate grasp_ft_s0_manifest.json + /tmp/ft_<Hand>.json (HANDS order) -> slurm_jobs/grasp_ft_manifest.json
#   python scripts/build_chain_manifest.py --pre slurm_jobs/grasp_ft_manifest.json --which best_rollout best_val last0 \
#       --cross-which best_val last0 --out slurm_jobs/grasp_ft_chain_manifest.json
#   bash slurm_jobs/submit_e24_grasp_ft.sh
set -euo pipefail
cd "$(dirname "$0")/.."
M=slurm_jobs/grasp_ft_chain_manifest.json
[[ -f $M ]] || { echo "build $M first (see header)" >&2; exit 1; }
sbatch -A ASC26008 -p gh -N 5 --array=0-3 -t 03:00:00 --job-name=grasp-ft --dependency=afterany:1061197 \
  --export=ALL,MANIFEST=$M,PACK=1 slurm_jobs/vista_train_manifest.sbatch
