#!/usr/bin/env python3
"""Per-dimension map of every task's policy observation and action vector.

The demo zarrs store flat obs/action rows with no column names; this builds
each env once and records, for every dimension, which observation term it
belongs to and what it is (joint name, xyz / quaternion component,
fingertip), and for every action dimension its actuated target and the
action term's settings. Complements `slurm_jobs/dump_schemas.sh` (term
names/dims only).

Writes outputs/analysis/spaces_reference.json and spaces_reference.md.
Run from the repo root: python scripts/dump_spaces.py [--device cuda:0]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

TASKS = [f"{fam}-{h}" for fam in ("Grasp", "InHand-Rotation") for h in ("Allegro", "LEAP", "Shadow", "Sharpa", "Wuji")]
QUAT = ["w", "x", "y", "z"]
XYZ = ["x", "y", "z"]


def entity_names(env, cfg_obj, kind: str) -> list[str]:
    """Names selected by a SceneEntityCfg (joint_names / body_names)."""
    ent = env.scene[cfg_obj.name]
    all_names = list(getattr(ent, f"{kind}_names"))
    ids = getattr(cfg_obj, f"{kind}_ids", slice(None))
    if isinstance(ids, slice):
        return all_names[ids]
    return [all_names[i] for i in ids]


def label_term(env, name: str, func: str, params: dict, dim: int, action_names: list[str]) -> list[str]:
    if func in ("joint_pos_rel", "joint_vel_rel"):
        joints = entity_names(env, params["asset_cfg"], "joint")
        what = "pos - default" if func == "joint_pos_rel" else "vel"
        return [f"{j} ({what})" for j in joints]
    if func == "keypoint_positions_in_base":
        bodies = entity_names(env, params["keypoints_cfg"], "body")
        return [f"{b}.{a}" for b in bodies for a in XYZ]
    if func == "last_action":
        return [f"prev action: {a}" for a in action_names]
    if dim == 4:
        return [f"{name}.{c}" for c in QUAT]
    if dim == 3:
        return [f"{name}.{c}" for c in XYZ]
    if dim == 1:
        return [name]
    return [f"{name}[{i}]" for i in range(dim)]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--device", default="cuda:0")
    args = ap.parse_args()

    from mjlab.envs import ManagerBasedRlEnv
    from mjlab.tasks.registry import load_env_cfg

    import mjlab_hand  # noqa: F401

    out: dict[str, dict] = {}
    for task in TASKS:
        cfg = load_env_cfg(task, play=True)
        cfg.scene.num_envs = 1
        env = ManagerBasedRlEnv(cfg=cfg, device=args.device)
        try:
            am = env.action_manager
            actions, action_terms = [], []
            for tname in am.active_terms:
                term = am._terms[tname]
                tcfg = term.cfg
                settings = {
                    k: v
                    for k, v in vars(tcfg).items()
                    if not k.startswith("_") and k not in ("class_type", "asset_name") and isinstance(v, (int, float, str, bool, tuple, list, dict, type(None)))
                }
                action_terms.append({"term": tname, "class": type(term).__name__, "settings": settings})
                actions += list(term.target_names)
            om = env.observation_manager
            group = "actor"
            obs, terms = [], []
            dims = om.group_obs_term_dim[group]
            for tname, tcfg, shape in zip(om.active_terms[group], om._group_obs_term_cfgs[group], dims, strict=True):
                dim = int(shape[0]) if isinstance(shape, (tuple, list)) else int(shape)
                func = getattr(tcfg.func, "__name__", type(tcfg.func).__name__)
                params = tcfg.params or {}
                labels = label_term(env, tname, func, params, dim, actions)
                if len(labels) != dim:
                    labels = [f"{tname}[{i}]" for i in range(dim)]
                extra = {k: v for k, v in params.items() if isinstance(v, (int, float, str))}
                terms.append({"term": tname, "func": func, "start": len(obs), "dim": dim, "params": extra})
                obs += [{"term": tname, "label": lab} for lab in labels]
            out[task] = {
                "obs_dim": len(obs),
                "action_dim": len(actions),
                "hand_joints": list(env.scene["hand"].joint_names),
                "obs_terms": terms,
                "obs": obs,
                "actions": actions,
                "action_terms": action_terms,
            }
            print(f"[INFO] {task}: obs {len(obs)}, action {len(actions)}")
        finally:
            env.close()

    root = Path("outputs/analysis")
    root.mkdir(parents=True, exist_ok=True)
    (root / "spaces_reference.json").write_text(json.dumps(out, indent=2, default=str))

    lines = ["# Observation / action dimensions per task", "", "Generated by `scripts/dump_spaces.py`.", ""]
    for task, d in out.items():
        lines += [f"## {task} (obs {d['obs_dim']}, action {d['action_dim']})", ""]
        for t in d["action_terms"]:
            lines.append(f"Action term `{t['term']}` ({t['class']}): {json.dumps(t['settings'], default=str)}")
        lines += ["", "| action dim | target |", "|---|---|"]
        lines += [f"| {i} | {a} |" for i, a in enumerate(d["actions"])]
        lines += ["", "| obs dims | term | function | params |", "|---|---|---|---|"]
        for t in d["obs_terms"]:
            lines.append(f"| {t['start']}-{t['start'] + t['dim'] - 1} | {t['term']} | {t['func']} | {t['params'] or ''} |")
        lines += ["", "| obs dim | meaning |", "|---|---|"]
        lines += [f"| {i} | {o['label']} |" for i, o in enumerate(d["obs"])]
        lines.append("")
    (root / "spaces_reference.md").write_text("\n".join(lines))
    print(f"[INFO] wrote {root}/spaces_reference.{{json,md}}")


if __name__ == "__main__":
    main()
