#!/usr/bin/env python3
"""Write `outputs/plots/INDEX.md`: what each figure shows and which script
regenerates it.

`GROUPS` is an ordered list of (glob pattern, description, regenerating
script); each file under `outputs/plots` is claimed by the first pattern
that matches it, so more specific patterns must come before broader ones.
`space_matched_pairs.png` (written by `compare_matched_embodiments.py`)
must stay above the `space_*.png` glob, since the rest of `space_*.png`
comes from `analyze_spaces.py` -- each file is claimed once.

See CHANGES.md items 6j (new) and 39 (added groups for the ambient-sweep
and separability result figures, which had no entry and landed
"Unclassified" with no record of which script regenerates them).
"""

from __future__ import annotations

import argparse
import fnmatch
from pathlib import Path

GROUPS: list[tuple[str, str, str]] = [
    (
        "comparison_all_runs.png",
        "RL training curves, all runs overlaid",
        "scripts/plot_training_curves.py",
    ),
    (
        "*_seeds.png",
        "Per-experiment RL training curve, mean +/- std across seeds",
        "scripts/plot_seed_curves.py",
    ),
    (
        "summary_grasp.png",
        "RL training summary across grasp tasks (seed-aggregated)",
        "scripts/plot_seed_curves.py",
    ),
    (
        "summary_rotation.png",
        "RL training summary across rotation tasks (seed-aggregated)",
        "scripts/plot_seed_curves.py",
    ),
    (
        "dp_scaling_grasp.png",
        "Diffusion-policy grasp success vs dataset size (data-scaling ablation)",
        "scripts/plot_diffusion_curves.py",
    ),
    (
        "dp_scaling_rotation.png",
        "Diffusion-policy rotation performance vs dataset size (data-scaling ablation)",
        "scripts/plot_diffusion_curves.py",
    ),
    (
        "dp_summary_grasp.png",
        "Diffusion-policy grasp summary across hands/scales",
        "scripts/plot_diffusion_curves.py",
    ),
    (
        "dp_summary_rotation.png",
        "Diffusion-policy rotation summary across hands/scales",
        "scripts/plot_diffusion_curves.py",
    ),
    (
        "dp_summary.png",
        "Diffusion-policy summary across all hands (1M vs 10M)",
        "scripts/plot_diffusion_curves.py",
    ),
    (
        "dp_*.png",
        "Per-hand diffusion-policy training/eval curves",
        "scripts/plot_diffusion_curves.py",
    ),
    (
        "mixed_matrix_*.png",
        "Mixed-embodiment one-hot conditioning grid (Allegro/LEAP data-size matrix)",
        "scripts/plot_mixed_matrix.py",
    ),
    (
        "ambient_sweep*.png",
        "Ambient-diffusion sigma* sweep: performance vs gating threshold",
        "scripts/plot_ambient_sweep.py",
    ),
    (
        "ambient_threshold.png",
        "Cross-embodiment action distance (W1) vs diffusion timestep",
        "scripts/measure_ambient_threshold.py",
    ),
    (
        "state_separability.png",
        "Embodiment separability from a single observation, incl. noised curve",
        "scripts/measure_state_separability.py",
    ),
    (
        "state_equivalence_tradeoff.png",
        "Adversarial invariance vs task-decode R^2, sweeping reversal strength",
        "scripts/train_state_equivalence.py",
    ),
    (
        "space_matched_pairs.png",
        "Allegro/LEAP per-dimension raw vs mean-centred Wasserstein-1 distance",
        "scripts/compare_matched_embodiments.py",
    ),
    (
        "space_*.png",
        "Observation/action space structure (term layout, PCA, action ranges)",
        "scripts/analyze_spaces.py",
    ),
    (
        "eval_curves.png",
        "In-training diffusion-policy env-eval curve for a single run",
        "scripts/watch_eval_diffusion.py",
    ),
    ("*grasp*.png", "RL training curve, single run", "scripts/plot_training_curves.py"),
    ("*rotation*.png", "RL training curve, single run", "scripts/plot_training_curves.py"),
]


def classify(path: Path) -> tuple[str, str] | None:
    for pattern, desc, script in GROUPS:
        if fnmatch.fnmatch(path.name, pattern):
            return desc, script
    return None


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--plots-dir", type=Path, default=Path("outputs/plots"))
    args = ap.parse_args()

    plots_dir = args.plots_dir.resolve()
    files = sorted(plots_dir.glob("*.png"))

    classified: list[tuple[Path, str, str]] = []
    unclassified: list[Path] = []
    for f in files:
        hit = classify(f)
        if hit is None:
            unclassified.append(f)
        else:
            desc, script = hit
            classified.append((f, desc, script))

    lines = [
        "# Plot index",
        "",
        "Auto-generated by `scripts/make_plot_index.py`. Do not edit by hand.",
        "",
        "| File | Description | Regenerated by |",
        "|---|---|---|",
    ]
    for f, desc, script in classified:
        lines.append(f"| `{f.name}` | {desc} | `{script}` |")

    if unclassified:
        lines.append("")
        lines.append("## Unclassified")
        lines.append("")
        for f in unclassified:
            lines.append(f"- `{f.name}`")

    out_path = plots_dir / "INDEX.md"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"[INFO] Wrote {out_path}")
    print(f"{len(classified)} classified, {len(unclassified)} unclassified")


if __name__ == "__main__":
    main()
